"""ALtered UrlStats and Url tabls

Revision ID: 98bebec1c59f
Revises: 0001_fixed_issues
Create Date: 2026-09-08 20:42:27.519562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98bebec1c59f'
down_revision: Union[str, Sequence[str], None] = '0001_fixed_issues'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expiry', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('urls_stats', 'expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls_stats', sa.Column('expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('urls', 'expiry')
    # ### end Alembic commands ###
