"""Added URLStats table and switched to SQLAlchemey 2.0

Revision ID: c4cca43c7b9f
Revises: 5089cff45e3e
Create Date: 2026-09-05 13:57:45.466117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cca43c7b9f'
down_revision: Union[str, Sequence[str], None] = '5089cff45e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_id')
    )
    op.alter_column('urls', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('urls', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_urls_code'), 'urls', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_code'), table_name='urls')
    op.alter_column('urls', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('urls', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('urls_stats')
    # ### end Alembic commands ###
